name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "Ride and control any mob"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  ridables:
    description: Reload config
    usage: /<command> reload
    aliases:
      - rideables
      - rideable
      - ridable

permissions:
  ridables.*:
    description: Gives every permission
    children:
      ridables.ride.*:
        description: Allows to ride every ridable mob
        children:
          ridables.ride.bat:
            description: Allows to ride ridable bats
            default: op
          ridables.ride.blaze:
            description: Allow to ride blazes
            default: op
          ridables.ride.cave_spider:
            description: Allow to ride cave spiders
            default: op
          ridables.ride.chicken:
            description: Allow to ride chickens
            default: op
          ridables.ride.cod:
            description: Allow to ride cod fish
            default: op
          ridables.ride.cow:
            description: Allow to ride cows
            default: op
          ridables.ride.creeper:
            description: Allow to ride creepers
            default: op
          ridables.ride.dolphin:
            description: Allow to ride dolphins
            default: op
          ridables.ride.drowned:
            description: Allow to ride drowned
            default: op
          ridables.ride.elder_guardian:
            description: Allow to ride elder guardians
            default: op
          ridables.ride.ender_dragon:
            description: Allow to ride ender dragon
            default: op
          ridables.ride.enderman:
            description: Allow to ride endermen
            default: op
          ridables.ride.endermite:
            description: Allow to ride endermites
            default: op
          ridables.ride.evoker:
            description: Allow to ride evokers
            default: op
          ridables.ride.ghast:
            description: Allow to ride ghast
            default: op
          ridables.ride.giant:
            description: Allow to ride giants
            default: op
          ridables.ride.guardian:
            description: Allow to ride guardians
            default: op
          ridables.ride.husk:
            description: Allow to ride husks
            default: op
          ridables.ride.illusioner:
            description: Allow to ride illusioners
            default: op
          ridables.ride.iron_golem:
            description: Allow to ride iron golems
            default: op
          ridables.ride.llama:
            description: Allow to ride llamas
            default: op
          ridables.ride.magma_cube:
            description: Allow to ride magma cubes
            default: op
          ridables.ride.mooshroom:
            description: Allow to ride mooshrooms
            default: op
          ridables.ride.ocelot:
            description: Allow to ride tamed ocelots
            default: op
          ridables.ride.parrot:
            description: Allow to ride parrots
            default: op
          ridables.ride.phantom:
            description: Allow to ride phantoms
            default: op
          ridables.ride.pig:
            description: Allow to ride pigs
            default: op
          ridables.ride.polar_bear:
            description: Allow to ride polar bears
            default: op
          ridables.ride.pufferfish:
            description: Allow to ride pufferfish
            default: op
          ridables.ride.rabbit:
            description: Allow to ride rabbits
            default: op
          ridables.ride.salmon:
            description: Allow to ride salmon
            default: op
          ridables.ride.sheep:
            description: Allow to ride sheep
            default: op
          ridables.ride.shulker:
            description: Allow to ride shulkers
            default: op
          ridables.ride.silverfish:
            description: Allow to ride silverfish
            default: op
          ridables.ride.skeleton:
            description: Allow to ride skeletons
            default: op
          ridables.ride.skeleton_horse:
            description: Allow to ride skeleton horses
            default: op
          ridables.ride.slime:
            description: Allow to ride slimes
            default: op
          ridables.ride.snow_golem:
            description: Allow to ride snowman
            default: op
          ridables.ride.spider:
            description: Allow to ride spiders
            default: op
          ridables.ride.squid:
            description: Allow to ride squids
            default: op
          ridables.ride.stray:
            description: Allow to ride strays
            default: op
          ridables.ride.tropical_fish:
            description: Allow to ride tropical fish
            default: op
          ridables.ride.turtle:
            description: Allow to ride turtles
            default: op
          ridables.ride.vex:
            description: Allow to ride vex
            default: op
          ridables.ride.villager:
            description: Allow to ride villagers
            default: op
          ridables.ride.vindicator:
            description: Allow to ride vindicators
            default: op
          ridables.ride.witch:
            description: Allow to ride witches
            default: op
          ridables.ride.wither:
            description: Allow to ride withers
            default: op
          ridables.ride.wither_skeleton:
            description: Allow to ride wither skeletons
            default: op
          ridables.ride.wolf:
            description: Allow to ride tamed wolves
            default: op
          ridables.ride.zombie:
            description: Allow to ride zombies
            default: op
          ridables.ride.zombie_horse:
            description: Allow to ride zombie horses
            default: op
          ridables.ride.zombie_pigman:
            description: Allow to ride zombie pigman
            default: op
          ridables.ride.zombie_villager:
            description: Allow to ride zombie villagers
            default: op
      ridables.shoot.*:
        description: Allows to make all ridables shoot
        default: op
        children:
          ridables.shoot.blaze:
            description: Allows to make blazes shoot fireballs
            default: op
          ridables.shoot.dolphin:
            description: Allows to make dolphins shoot spit
            default: op
          ridables.shoot.drowned:
            description: Allows to make drownedd throw tridents
            default: op
          ridables.shoot.ghast:
            description: Allows to make ghasts shoot fireballs
            default: op
          ridables.shoot.phantom:
            description: Allows to make phantoms shoot flames
            default: op
          ridables.shoot.shulker:
            description: Allows to make withers shoot shulker bullets
            default: op
          ridables.shoot.snow_golem:
            description: Allows to make snow golems shoot snowballs
            default: op
          ridables.shoot.spider:
            description: Allows to make spiders shoot cob webs
            default: op
          ridables.shoot.witch:
            description: Allows to make witches throw potions of harming
            default: op
          ridables.shoot.wither:
            description: Allows to make withers shoot skulls
            default: op
      ridables.special.*:
        description: Allows to make all supported creatures do their special
        default: op
        children:
          ridables.special.creeper:
            description:  Allows to use all special creeper abilities
            default: op
            children:
              ridables.special.creeper.ignite:
                description: Allows to make creepers ignite
                default: op
              ridables.special.creeper.powered:
                description: Allows to toggle creeper powered state
                default: op
          ridables.special.dolphin:
            description: Allows to make dolphins dash
            default: op
          ridables.special.enderman:
            description: Allows to make endermen pick up and place blocks
            default: op
          ridables.special.evoker:
            description: Allows to make evokers cast fangs spell
            default: op
          ridables.special.magma_cube:
            description: Allows to make magma cubes jump higher
            default: op
          ridables.special.slime:
            description: Allows to make slimes jump higher
            default: op
          ridables.special.squid:
            description: Allows to make squids squirt ink
            default: op
      ridables.collect.*:
        description: Allows to collect all ridables in water buckets
        default: op
        children:
          ridables.collect.dolphin:
            description: Allows to collect dolphins in water buckets
            default: op
          ridables.collect.squid:
            description: Allows to collect squids in water buckets
            default: op
          ridables.collect.turtle:
            description: Allows to collect turtles in water buckets
            default: op
      ridables.command.*:
        description: Allows to use all commands
        default: op
        children:
          ridables.command.ridables:
            description: Allows to reload config
            default: op
